{{- if .Values.ceph.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-rook-ceph-conf
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      activeDeadlineSeconds: 100
      containers:
        - name: sync-rook-ceph-conf
          image: {{ include "cinder.kolla-toolbox.image" . }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - >
              python /tmp/sync-ceph-endpoint.py;
              python /tmp/sync-ceph-secrets.py
          env:
            - name: KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: ROOK_CEPH_CLUSTER_NAMESPACE
              value: {{ .Values.ceph.cephClusterNamespace }}
            - name: OS_CEPH_MON_CONFIGMAP
              value: "ceph-monitor-endpoints"
            - name: ROOK_CEPH_CLIENT_NAME
              value: {{ .Values.ceph.cephClientName }}
            - name: OS_CEPH_CLIENT_SECRET
              value: {{ printf "ceph-%s" .Values.ceph.cephClientName }}
          volumeMounts:
          - mountPath: /tmp
            name: pod-tmp
          - mountPath: /tmp/sync-ceph-endpoint.py
            name: cinder-bin
            subPath: sync-ceph-endpoint.py
          - mountPath: /tmp/sync-ceph-secrets.py
            name: cinder-bin
            subPath: sync-ceph-secrets.py
      restartPolicy: OnFailure
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      volumes:
        - emptyDir: {}
          name: pod-tmp
        - name: cinder-bin
          configMap:
            defaultMode: 0755
            name: cinder-bin
{{- end }}
